In [241]:
import pandas as pd

In [242]:
cols=[
    'age', 'workclass', 'fnlwgt', 'education', 'education-num',
    'martial-status', 'occupation', 'relationship', 'race', 'sex',
    'capital-gain', 'capital-loss', 'hours-per-week', 'native-country','salary'
]

In [243]:
trd=pd.read_csv(
    'adult.data',
    names=cols,
    sep=',',
    engine="python"
)

In [244]:
tsd=pd.read_csv(
    'adult.test',
    names=cols,
    sep=',',
    engine="python"
)

In [245]:
trd.shape

(32561, 15)

In [246]:
tsd.shape

(16282, 15)

In [247]:
trd.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
martial-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
salary            0
dtype: int64

In [248]:
tsd.isnull().sum()

age               0
workclass         1
fnlwgt            1
education         1
education-num     1
martial-status    1
occupation        1
relationship      1
race              1
sex               1
capital-gain      1
capital-loss      1
hours-per-week    1
native-country    1
salary            1
dtype: int64

In [249]:
tsd.head()

,age,workclass,fnlwgt,education,education-num,martial-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,|1x3 Cross validator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,25,Private,226802.0,11th,7.0,Never-married,Machine-op-inspct,Own-child,Black,Male,0.0,0.0,40.0,United-States,<=50K.
2,38,Private,89814.0,HS-grad,9.0,Married-civ-spouse,Farming-fishing,Husband,White,Male,0.0,0.0,50.0,United-States,<=50K.
3,28,Local-gov,336951.0,Assoc-acdm,12.0,Married-civ-spouse,Protective-serv,Husband,White,Male,0.0,0.0,40.0,United-States,>50K.
4,44,Private,160323.0,Some-college,10.0,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688.0,0.0,40.0,United-States,>50K.

In [250]:
print(tsd['salary'].unique())

<StringArray>
[nan, ' <=50K.', ' >50K.']
Length: 3, dtype: str

In [251]:
trd.isin([' ?']).sum()

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
martial-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
salary               0
dtype: int64

In [252]:
tsd.isin([' ?']).sum()

age                 0
workclass         963
fnlwgt              0
education           0
education-num       0
martial-status      0
occupation        966
relationship        0
race                0
sex                 0
capital-gain        0
capital-loss        0
hours-per-week      0
native-country    274
salary              0
dtype: int64

In [253]:
print(trd['workclass'].unique())

<StringArray>
[       ' State-gov', ' Self-emp-not-inc',          ' Private',
      ' Federal-gov',        ' Local-gov',                ' ?',
     ' Self-emp-inc',      ' Without-pay',     ' Never-worked']
Length: 9, dtype: str

In [254]:
trd=trd.replace(' ?', pd.NA)
trd=trd.dropna()

In [255]:
tsd=tsd.replace(' ?', pd.NA)
tsd=tsd.dropna()

In [256]:
print(tsd['salary'].unique())

<StringArray>
[' <=50K.', ' >50K.']
Length: 2, dtype: str

In [257]:
print(trd['workclass'].unique())
print(tsd['workclass'].unique())

<StringArray>
[       ' State-gov', ' Self-emp-not-inc',          ' Private',
      ' Federal-gov',        ' Local-gov',     ' Self-emp-inc',
      ' Without-pay']
Length: 7, dtype: str
<StringArray>
[         ' Private',        ' Local-gov', ' Self-emp-not-inc',
      ' Federal-gov',        ' State-gov',     ' Self-emp-inc',
      ' Without-pay']
Length: 7, dtype: str

In [258]:
trd.head()

,age,workclass,fnlwgt,education,education-num,martial-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [259]:
pd.crosstab(trd['education'], trd['education-num'])

education-num,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
education,,,,,,,,,,,,,,,,
10th,0,0,0,0,0,820,0,0,0,0,0,0,0,0,0,0
11th,0,0,0,0,0,0,1048,0,0,0,0,0,0,0,0,0
12th,0,0,0,0,0,0,0,377,0,0,0,0,0,0,0,0
1st-4th,0,151,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5th-6th,0,0,288,0,0,0,0,0,0,0,0,0,0,0,0,0
7th-8th,0,0,0,557,0,0,0,0,0,0,0,0,0,0,0,0
9th,0,0,0,0,455,0,0,0,0,0,0,0,0,0,0,0
Assoc-acdm,0,0,0,0,0,0,0,0,0,0,0,1008,0,0,0,0
Assoc-voc,0,0,0,0,0,0,0,0,0,0,1307,0,0,0,0,0
Bachelors,0,0,0,0,0,0,0,0,0,0,0,0,5044,0,0,0
Doctorate,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,375
HS-grad,0,0,0,0,0,0,0,0,9840,0,0,0,0,0,0,0
Masters,0,0,0,0,0,0,0,0,0,0,0,0,0,1627,0,0
Preschool,45,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Prof-school,0,0,0,0,0,0,0,0,0,0,0,0,0,0,542,0
Some-college,0,0,0,0,0,0,0,0,0,6678,0,0,0,0,0,0

In [260]:
trd=trd.drop(columns=['education'])
tsd=tsd.drop(columns=['education'])

In [261]:
trd.shape

(30162, 14)

In [262]:
tsd.shape

(15060, 14)

In [263]:
for col in trd.select_dtypes(include=['object', 'string']).columns:
    trd[col]=trd[col].str.strip()

In [264]:
for col in tsd.select_dtypes(include=['object', 'string']).columns:
    tsd[col]=tsd[col].str.strip()

In [265]:
print(trd['workclass'].unique())
print(tsd['workclass'].unique())

<StringArray>
[       'State-gov', 'Self-emp-not-inc',          'Private',
      'Federal-gov',        'Local-gov',     'Self-emp-inc',
      'Without-pay']
Length: 7, dtype: str
<StringArray>
[         'Private',        'Local-gov', 'Self-emp-not-inc',
      'Federal-gov',        'State-gov',     'Self-emp-inc',
      'Without-pay']
Length: 7, dtype: str

In [266]:
print(tsd['salary'].unique())

<StringArray>
['<=50K.', '>50K.']
Length: 2, dtype: str

In [267]:
trd.head()

,age,workclass,fnlwgt,education-num,martial-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [268]:
print(trd['sex'].unique())

<StringArray>
['Male', 'Female']
Length: 2, dtype: str

In [269]:
print(trd['salary'].unique())

<StringArray>
['<=50K', '>50K']
Length: 2, dtype: str

In [270]:
print(tsd['salary'].unique())

<StringArray>
['<=50K.', '>50K.']
Length: 2, dtype: str

In [271]:
trd['sex']=trd['sex'].map({'Male':0, 'Female':1})
tsd['sex']=tsd['sex'].map({'Male':0, 'Female':1})

In [272]:
for val in trd['salary'].unique():
    print(repr(val))

'<=50K'
'>50K'

In [273]:
for val in tsd['salary'].unique():
    print(repr(val))

'<=50K.'
'>50K.'

In [274]:
trd['salary'] = trd['salary'].map({'<=50K':0, '>50K':1})

In [275]:
tsd['salary'] = tsd['salary'].map({'<=50K.':0, '>50K.':1})

In [276]:
print(trd['salary'].value_counts())

salary
0    22654
1     7508
Name: count, dtype: int64

In [277]:
print(tsd['salary'].value_counts())

salary
0    11360
1     3700
Name: count, dtype: int64

In [278]:
print(tsd['salary'].unique())

[0 1]

In [279]:
trd.head()

,age,workclass,fnlwgt,education-num,martial-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,13,Never-married,Adm-clerical,Not-in-family,White,0,2174,0,40,United-States,0
1,50,Self-emp-not-inc,83311,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,0,13,United-States,0
2,38,Private,215646,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,0,40,United-States,0
3,53,Private,234721,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,0,40,United-States,0
4,28,Private,338409,13,Married-civ-spouse,Prof-specialty,Wife,Black,1,0,0,40,Cuba,0

In [280]:
tsd.head()

,age,workclass,fnlwgt,education-num,martial-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
1,25,Private,226802.0,7.0,Never-married,Machine-op-inspct,Own-child,Black,0,0.0,0.0,40.0,United-States,0
2,38,Private,89814.0,9.0,Married-civ-spouse,Farming-fishing,Husband,White,0,0.0,0.0,50.0,United-States,0
3,28,Local-gov,336951.0,12.0,Married-civ-spouse,Protective-serv,Husband,White,0,0.0,0.0,40.0,United-States,1
4,44,Private,160323.0,10.0,Married-civ-spouse,Machine-op-inspct,Husband,Black,0,7688.0,0.0,40.0,United-States,1
6,34,Private,198693.0,6.0,Never-married,Other-service,Not-in-family,White,0,0.0,0.0,30.0,United-States,0

In [282]:
trd.to_pickle('adult_train_clean.pkl')

In [284]:
tsd.to_pickle('adult_test_clean.pkl')